workflows:
  flutter-android:
    name: Build Flutter App (Android)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter Dependencies
        script: flutter pub get
      - name: Clean Previous Build (Fix Issues)
        script: flutter clean  # Clears old build files
      - name: Build APK
        script: flutter build apk --release --verbose
      - name: Build AAB
        script: flutter build appbundle --verbose
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
