workflows:
  flutter-android:
    name: Build Flutter App (Android)
    max_build_duration: 60
    environment:
      flutter: stable
      java: 11  # Ensure Codemagic uses Java 11
    scripts:
      - name: Get Flutter Dependencies
        script: flutter pub get
      - name: Clean Previous Build
        script: flutter clean
      - name: Update Gradle
        script: cd android && ./gradlew wrapper --gradle-version 7.3.3 --distribution-type all
      - name: Build APK
        script: flutter build apk --release --verbose
      - name: Build AAB
        script: flutter build appbundle --verbose
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
